# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    app.translation.loader.foo:
        class: AppBundle\Translation\Loader\FooFileLoader
        tags:
            - { name: 'translation.loader', alias: 'foo' }
